### ISSUE TITLE
Issue with script version

### ISSUE THREAD

**Issue by YuriiShchyrba** [DataDog/test-visibility-gitlab-script#12]
I think you need to change version of script in Readme Usage section - main branch, tag v.1.2.4 and tag v.1.2.3 all pointing to v.1.2.3:

```
test_node:
  image: node:latest
  script:
    - LANGUAGES="js" SITE="datadoghq.com" API_KEY="YOUR_API_KEY_SECRET" source <(curl -Ls https://github.com/DataDog/test-optimization-gitlab-script/releases/download/v1.2.3/script.sh)
    - npm run test
```

Unless expeted.
